first_app/config/routes.rb
Rails.application.routes.draw do
  resources :laptops
  # get '/' => 'home#index'
  root 'utilities#index'

  get 'utilities/get_stock' => 'utilities#get_stock'
  get 'utilities/show_stock' => 'utilities#show_stock'



  get 'utilities/stock' => 'utilities#stock'
  get 'utilities/weather'
  get 'utilities/lotto'
  get 'utilities' => 'utilities#index'

  get '/animals' => 'animals#index'
  get '/animals/cat' => 'animals#cat'
  get '/animals/dog' => 'animals#dog'
  get '/animals/firefox' => 'animals#firefox'

  get '/musics' => 'musics#index'
  get '/musics/1' => 'musics#music_1'
  get '/musics/2' => 'muscis#music_2'
end

first_app/app/models/laptop.rb
class Laptop < ApplicationRecord
end

first_app/app/models/member.rb
class Member < ApplicationRecord
end

first_app/app/models/movie.rb
class Movie < ApplicationRecord
end

first_app/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def cat
  end
  
  def dog
  end
  
  def firefox
    # app/views/컨트롤러이름_dir/액션.html.erb
  end
  
  def index
  end
  
 
end

first_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # render html: "당신이 접속한 IP는 #{request.remote_ip} 입니다."
  end


end

first_app/app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: [:show, :edit, :update, :destroy]

  # GET /laptops
  # GET /laptops.json
  def index
    @laptops = Laptop.all
  end

  # GET /laptops/1
  # GET /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops
  # POST /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to @laptop, notice: 'Laptop was successfully created.' }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1
  # PATCH/PUT /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to @laptop, notice: 'Laptop was successfully updated.' }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1
  # DELETE /laptops/1.json
  def destroy
    @laptop.destroy
    respond_to do |format|
      format.html { redirect_to laptops_url, notice: 'Laptop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laptop_params
      params.require(:laptop).permit(:company, :inch, :year)
    end
end

first_app/app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
  end
  
  def music_1
  end
  
  def music_2
  end
  
  def music_3
  end
end

first_app/app/controllers/utilities_controller.rb
require 'open-uri'
require 'json'

class UtilitiesController < ApplicationController
  def stock
  end

  def weather
  end

  def lotto
    url = 'http://www.nlotto.co.kr/common.do?method=getLottoNumber&drwNo=801'
    res = open(url)
    text = res.read
        lotto_info = JSON.parse(text)

    real_numbers = []

    lotto_info.each do |key, value|
      if key.include? 'drwtNo'
        real_numbers << value
      end
    end

    real_numbers.sort!
    bonus_number = lotto_info['bnusNo']
    my_numbers = (1..45).to_a.sample(6).sort

    match_numbers = real_numbers & my_numbers
    match_count = match_numbers.count

    if match_count == 6
      @rank = '1등'
    elsif match_count == 5 && my_numbers.include?(bonus_number)
      @rank = '2등'
    elsif match_count == 5
      @rank = '3등'
    elsif match_count == 4
      @rank = '4등'
    elsif match_count == 3
      @rank = '5등'
    else
      @rank = '다음 기회에..'
    end

    @my_numbers = my_numbers
    @real_numbers = real_numbers
    @match_numbers = match_numbers

  end

  def index
  end

  def get_stock
    # 사용자가 주식 심볼 입력하는 페이지

  end

  def show_stock
    #get_stock 에서 입력한 data로 주식 정보 찾아서 보여주기
    #example params['input_symbol']
    symbol = params[:input_symbol]
    @stock = StockQuote::Stock.quote(symbol)
    # if @stock.nil?
    #   redirect_to 'utilities/get_stock'
    # end


  end



end

first_app/app/helpers/animals_helper.rb
module AnimalsHelper
end

first_app/app/helpers/home_helper.rb
module HomeHelper
end

first_app/app/helpers/laptops_helper.rb
module LaptopsHelper
end

first_app/app/helpers/musics_helper.rb
module MusicsHelper
end

first_app/app/helpers/utilities_helper.rb
module UtilitiesHelper
end

first_app/app/views/animals/cat.html.erb
<h1>Hacking Cat</h1>

<img src='https://media.giphy.com/media/o0vwzuFwCGAFO/giphy.gif' alt='hacking cat' />

first_app/app/views/animals/dog.html.erb
<h1>Hacking Dog</h1>

<img src='https://memegenerator.net/img/instances/65463177.jpg' alt='hacking dog' />

first_app/app/views/animals/firefox.html.erb
<h1>Firefox</h1>

<img src='https://i.ytimg.com/vi/b6dT4kyVUuY/maxresdefault.jpg' alt='cute firefox' />

first_app/app/views/animals/index.html.erb
<h1>My Animals</h1>
<ul>
  <li><a href='/animals/cat'>Hacking Cat</a></li>
  <li><a href='/animals/dog'>Hacking Dog</a></li>
  <li><a href='/animals/firefox'>Firefox</a></li>
</ul>

first_app/app/views/laptops/_form.html.erb
<%= form_for(laptop) do |f| %>
  <% if laptop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
      <% laptop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :inch %>
    <%= f.text_field :inch %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

first_app/app/views/laptops/edit.html.erb
<h1>Editing Laptop</h1>

<%= render 'form', laptop: @laptop %>

<%= link_to 'Show', @laptop %> |
<%= link_to 'Back', laptops_path %>

first_app/app/views/laptops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Laptops</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Inch</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laptops.each do |laptop| %>
      <tr>
        <td><%= laptop.company %></td>
        <td><%= laptop.inch %></td>
        <td><%= laptop.year %></td>
        <td><%= link_to 'Show', laptop %></td>
        <td><%= link_to 'Edit', edit_laptop_path(laptop) %></td>
        <td><%= link_to 'Destroy', laptop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laptop', new_laptop_path %>

first_app/app/views/laptops/new.html.erb
<h1>New Laptop</h1>

<%= render 'form', laptop: @laptop %>

<%= link_to 'Back', laptops_path %>

first_app/app/views/laptops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @laptop.company %>
</p>

<p>
  <strong>Inch:</strong>
  <%= @laptop.inch %>
</p>

<p>
  <strong>Year:</strong>
  <%= @laptop.year %>
</p>

<%= link_to 'Edit', edit_laptop_path(@laptop) %> |
<%= link_to 'Back', laptops_path %>

first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

first_app/app/views/musics/index.html.erb
<h1>neo's playlists</h1>

<ul>
  <li><a href='/musics/1'>MCR-Welcome to the black parade</a></li>
  <li></li>
  <li></li>
</ul>

first_app/app/views/musics/music_1.html.erb
<h1>Welcome to the black parade</h1>

<iframe width="1060" height="515" src="https://www.youtube.com/embed/RRKJiM9Njr8?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<p>When I was a young boy
My father took me into the city
To see a marching band
He said, son, when you grow up
Would you be the savior of the broken
The beaten, and the damned?
He said, will you defeat them
Your demons and all the non-believers?
The plans that they have made?
Because one day I'll leave you
A phantom to lead you in the summer
To join the black parade
When I was a young boy
My father took me into the city
To see a marching band
He said, son, when you grow up
You will be the savior of the broken
The beaten, and the damned?
Sometimes I get the feeling
She's watching over me
And other times I feel like I should go
And through it all
The rise and fall
The bodies in the streets
And when you're gone, we want you all to know
We'll carry on, we'll carry on
And though you're dead and gone, believe me
Your memory will carry on
We'll carry on
And in my heart I can't contain it
The anthem won't explain it
A world that sends you reeling
From decimated dreams
Your misery and hate will kill us all
So paint it black
And take it back
Let's shout it loud and clear
Defiant to the end
We hear the call
To carry on
We'll carry on
And though you're dead and gone, believe me
Your memory will carry on
We'll carry on
And though you're broken and defeated
Your weary widow marches
On and on, we carry through the fears
(Oh, oh, oh)
Disappointed faces of your peers
(Oh, oh, oh)
Take a look at me
'Cause I could not care at all
Do or die
You'll never make me
Because the world
Will never take my heart
You can try
You'll never break me
We wanna all
We want to play this part
Won't explain
Or say I'm sorry
I'm unashamed
I'm gonna show my scar
Give a cheer
For all the broken
Listen here
Because it's who we are
I'm just a man
I'm not a hero
Just a boy who had to sing this song
I'm just a man
I'm not a hero
I don't care
We'll carry on
We'll carry on
And though your dead and gone, believe me
Your memory will carry on
We'll carry on
And though you're broken and defeated
Your weary widow marches on
Do or die
You'll never make me
Because the world
Will never take my heart
You can try
You'll never break me
We wanna know
We want to play this part
Do or die (we'll carry on)
You'll never make me (we'll carry on)
Because the world (we'll carry on)
Will never take my heart
You can try
You'll never break me
We wanna all
We want to play this part (we'll carry on)
</p>
<p>
작사: Bob Bryar / Frank Iero / Gerard Way / Michael Way / Ray Toro
웰컴 투 더 블랙 퍼레이드 가사 © Blow The Doors Off Chicago</p>

first_app/app/views/musics/music_2.html.erb
<h1>shed a light</h1>